version: '3.5'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
  frontend:
    build:
      context: ./apolloui
      dockerfile: Dockerfile
      target: frontend
